'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
'
Namespace FeeSchemaService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FeeSchemaServiceBinding", [Namespace]:="http://webservice.aws.soft.eniac/")>  _
    Partial Public Class FeeSchemaServiceService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private assignFeeSchema2CardAcceptorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getFeeSchemaListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.My.MySettings.Default.PSPTejarat_FeeSchemaService_FeeSchemaServiceService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event assignFeeSchema2CardAcceptorCompleted As assignFeeSchema2CardAcceptorCompletedEventHandler
        
        '''<remarks/>
        Public Event getFeeSchemaListCompleted As getFeeSchemaListCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function assignFeeSchema2CardAcceptor(<System.Xml.Serialization.XmlElementAttribute("assignFeeSchema2CardAcceptor", [Namespace]:="http://webservice.aws.soft.eniac/")> ByVal assignFeeSchema2CardAcceptor1 As assignFeeSchema2CardAcceptor) As <System.Xml.Serialization.XmlElementAttribute("assignFeeSchema2CardAcceptorResponse", [Namespace]:="http://webservice.aws.soft.eniac/")> assignFeeSchema2CardAcceptorResponse
            Dim results() As Object = Me.Invoke("assignFeeSchema2CardAcceptor", New Object() {assignFeeSchema2CardAcceptor1})
            Return CType(results(0),assignFeeSchema2CardAcceptorResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub assignFeeSchema2CardAcceptorAsync(ByVal assignFeeSchema2CardAcceptor1 As assignFeeSchema2CardAcceptor)
            Me.assignFeeSchema2CardAcceptorAsync(assignFeeSchema2CardAcceptor1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub assignFeeSchema2CardAcceptorAsync(ByVal assignFeeSchema2CardAcceptor1 As assignFeeSchema2CardAcceptor, ByVal userState As Object)
            If (Me.assignFeeSchema2CardAcceptorOperationCompleted Is Nothing) Then
                Me.assignFeeSchema2CardAcceptorOperationCompleted = AddressOf Me.OnassignFeeSchema2CardAcceptorOperationCompleted
            End If
            Me.InvokeAsync("assignFeeSchema2CardAcceptor", New Object() {assignFeeSchema2CardAcceptor1}, Me.assignFeeSchema2CardAcceptorOperationCompleted, userState)
        End Sub
        
        Private Sub OnassignFeeSchema2CardAcceptorOperationCompleted(ByVal arg As Object)
            If (Not (Me.assignFeeSchema2CardAcceptorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent assignFeeSchema2CardAcceptorCompleted(Me, New assignFeeSchema2CardAcceptorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function getFeeSchemaList(<System.Xml.Serialization.XmlElementAttribute("getFeeSchemaList", [Namespace]:="http://webservice.aws.soft.eniac/")> ByVal getFeeSchemaList1 As getFeeSchemaList) As <System.Xml.Serialization.XmlElementAttribute("getFeeSchemaListResponse", [Namespace]:="http://webservice.aws.soft.eniac/")> getFeeSchemaListResponse
            Dim results() As Object = Me.Invoke("getFeeSchemaList", New Object() {getFeeSchemaList1})
            Return CType(results(0),getFeeSchemaListResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getFeeSchemaListAsync(ByVal getFeeSchemaList1 As getFeeSchemaList)
            Me.getFeeSchemaListAsync(getFeeSchemaList1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getFeeSchemaListAsync(ByVal getFeeSchemaList1 As getFeeSchemaList, ByVal userState As Object)
            If (Me.getFeeSchemaListOperationCompleted Is Nothing) Then
                Me.getFeeSchemaListOperationCompleted = AddressOf Me.OngetFeeSchemaListOperationCompleted
            End If
            Me.InvokeAsync("getFeeSchemaList", New Object() {getFeeSchemaList1}, Me.getFeeSchemaListOperationCompleted, userState)
        End Sub
        
        Private Sub OngetFeeSchemaListOperationCompleted(ByVal arg As Object)
            If (Not (Me.getFeeSchemaListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getFeeSchemaListCompleted(Me, New getFeeSchemaListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservice.aws.soft.eniac/")>  _
    Partial Public Class assignFeeSchema2CardAcceptor
        
        Private arg0Field As feeSchemaRq
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property arg0() As feeSchemaRq
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Partial Public Class feeSchemaRq
        
        Private cardAcceptorField As cardAcceptorDTO
        
        Private feeSchemaField As feeSchema
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cardAcceptor() As cardAcceptorDTO
            Get
                Return Me.cardAcceptorField
            End Get
            Set
                Me.cardAcceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property feeSchema() As feeSchema
            Get
                Return Me.feeSchemaField
            End Get
            Set
                Me.feeSchemaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Partial Public Class cardAcceptorDTO
        
        Private businessCodeField As Short
        
        Private idField As String
        
        Private instField As institutionDTO
        
        Private paymentMethodField As paymentMethodType
        
        Private paymentMethodFieldSpecified As Boolean
        
        Private reconciliationCycleLenghtField As Short
        
        Private setlAcntField As externalAccountDTO
        
        Private settlementMethodField As settlementMethodType
        
        Private settlementMethodFieldSpecified As Boolean
        
        Private settlementTimeField As String
        
        Private statusField As activeInactive
        
        Private statusFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property businessCode() As Short
            Get
                Return Me.businessCodeField
            End Get
            Set
                Me.businessCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property inst() As institutionDTO
            Get
                Return Me.instField
            End Get
            Set
                Me.instField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property paymentMethod() As paymentMethodType
            Get
                Return Me.paymentMethodField
            End Get
            Set
                Me.paymentMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property paymentMethodSpecified() As Boolean
            Get
                Return Me.paymentMethodFieldSpecified
            End Get
            Set
                Me.paymentMethodFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property reconciliationCycleLenght() As Short
            Get
                Return Me.reconciliationCycleLenghtField
            End Get
            Set
                Me.reconciliationCycleLenghtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property setlAcnt() As externalAccountDTO
            Get
                Return Me.setlAcntField
            End Get
            Set
                Me.setlAcntField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property settlementMethod() As settlementMethodType
            Get
                Return Me.settlementMethodField
            End Get
            Set
                Me.settlementMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property settlementMethodSpecified() As Boolean
            Get
                Return Me.settlementMethodFieldSpecified
            End Get
            Set
                Me.settlementMethodFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property settlementTime() As String
            Get
                Return Me.settlementTimeField
            End Get
            Set
                Me.settlementTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property status() As activeInactive
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Partial Public Class institutionDTO
        
        Private institutionAddressField As String
        
        Private institutionCellphoneNumberField As String
        
        Private institutionEmailAddressField As String
        
        Private institutionIDField As String
        
        Private institutionIINField As String
        
        Private institutionLatinAddressField As String
        
        Private institutionLatinNameField As String
        
        Private institutionNameField As String
        
        Private institutionPhoneField As String
        
        Private institutionTypeField As institutionType
        
        Private institutionTypeFieldSpecified As Boolean
        
        Private institutionWebAddressField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionAddress() As String
            Get
                Return Me.institutionAddressField
            End Get
            Set
                Me.institutionAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionCellphoneNumber() As String
            Get
                Return Me.institutionCellphoneNumberField
            End Get
            Set
                Me.institutionCellphoneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionEmailAddress() As String
            Get
                Return Me.institutionEmailAddressField
            End Get
            Set
                Me.institutionEmailAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionID() As String
            Get
                Return Me.institutionIDField
            End Get
            Set
                Me.institutionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionIIN() As String
            Get
                Return Me.institutionIINField
            End Get
            Set
                Me.institutionIINField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionLatinAddress() As String
            Get
                Return Me.institutionLatinAddressField
            End Get
            Set
                Me.institutionLatinAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionLatinName() As String
            Get
                Return Me.institutionLatinNameField
            End Get
            Set
                Me.institutionLatinNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionName() As String
            Get
                Return Me.institutionNameField
            End Get
            Set
                Me.institutionNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionPhone() As String
            Get
                Return Me.institutionPhoneField
            End Get
            Set
                Me.institutionPhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionType() As institutionType
            Get
                Return Me.institutionTypeField
            End Get
            Set
                Me.institutionTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property institutionTypeSpecified() As Boolean
            Get
                Return Me.institutionTypeFieldSpecified
            End Get
            Set
                Me.institutionTypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property institutionWebAddress() As String
            Get
                Return Me.institutionWebAddressField
            End Get
            Set
                Me.institutionWebAddressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Public Enum institutionType
        
        '''<remarks/>
        CardAcceptor
        
        '''<remarks/>
        [Operator]
        
        '''<remarks/>
        FinancialInstitution
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservice.aws.soft.eniac/")>  _
    Partial Public Class getFeeSchemaListResponse
        
        Private returnField As feeSchemaRs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property [return]() As feeSchemaRs
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Partial Public Class feeSchemaRs
        
        Private feeSchemaListField() As feeSchema
        
        Private responseCodeField As responseCode
        
        Private responseCodeFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("feeSchemaList", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property feeSchemaList() As feeSchema()
            Get
                Return Me.feeSchemaListField
            End Get
            Set
                Me.feeSchemaListField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property responseCode() As responseCode
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property responseCodeSpecified() As Boolean
            Get
                Return Me.responseCodeFieldSpecified
            End Get
            Set
                Me.responseCodeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Partial Public Class feeSchema
        
        Private expirationDateField As Date
        
        Private expirationDateFieldSpecified As Boolean
        
        Private idField As Integer
        
        Private nameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property expirationDate() As Date
            Get
                Return Me.expirationDateField
            End Get
            Set
                Me.expirationDateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property expirationDateSpecified() As Boolean
            Get
                Return Me.expirationDateFieldSpecified
            End Get
            Set
                Me.expirationDateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Public Enum responseCode
        
        '''<remarks/>
        DoneSuccessfully
        
        '''<remarks/>
        SystemMalfunction
        
        '''<remarks/>
        ErrorDuringPersistance
        
        '''<remarks/>
        ErrorLoadingDataFromDatabase
        
        '''<remarks/>
        ErrorDuringGettingSequence
        
        '''<remarks/>
        ErrorDuringUpdatingRecord
        
        '''<remarks/>
        ErrorDuringDeletingRecord
        
        '''<remarks/>
        Unable2Connect2Database
        
        '''<remarks/>
        UnabletoGenerateNextSequenceID
        
        '''<remarks/>
        CardAcceptorIdNotFound
        
        '''<remarks/>
        CardAcceptorInstitutionNotFound
        
        '''<remarks/>
        CardAcceptorInstitutionExternalAccountNotFound
        
        '''<remarks/>
        CardAcceptorHaventAnyTerminal
        
        '''<remarks/>
        CardAcceptorIdIsNotSpecified
        
        '''<remarks/>
        CardAcceptorReconciliationCycleLenghtIsNotSpecified
        
        '''<remarks/>
        CardAcceptorSettlementMethodIsNotSpecified
        
        '''<remarks/>
        CardAcceptorSettlementMethodInvalid
        
        '''<remarks/>
        CardAcceptorStatusIsNotSpecified
        
        '''<remarks/>
        CardAcceptorStatusInvalid
        
        '''<remarks/>
        CardAcceptorSettlementTimeIsNotSpecified
        
        '''<remarks/>
        DuplicateCardAcceptorId
        
        '''<remarks/>
        CardAcceptorIsNotSpecified
        
        '''<remarks/>
        CardAcceptorPaymentMethodIsNotSpecified
        
        '''<remarks/>
        CardAcceptorPaymentMethodInvalid
        
        '''<remarks/>
        ExternalAccountNumberIsNotSpecified
        
        '''<remarks/>
        ExternalAccountTitleIsNotSpecified
        
        '''<remarks/>
        ExternalAccountTypeIsNotSpecified
        
        '''<remarks/>
        ExternalAccountTypeInvalid
        
        '''<remarks/>
        ExternalAccountIsNotSpecified
        
        '''<remarks/>
        FeeSchemaIdIsNotSpecified
        
        '''<remarks/>
        FeeSchemaIsNotSpecified
        
        '''<remarks/>
        CannotReadFeeSchemaList
        
        '''<remarks/>
        FeeSchemaNotFound
        
        '''<remarks/>
        InstitutionAddressIsNotSpecified
        
        '''<remarks/>
        InstitutionNameIsNotSpecified
        
        '''<remarks/>
        InstitutionTypeIsNotSpecified
        
        '''<remarks/>
        InstitutionTypeInvalid
        
        '''<remarks/>
        InstitutionIsNotSpecified
        
        '''<remarks/>
        TerminalIDNotFound
        
        '''<remarks/>
        TerminalIsNotSpecified
        
        '''<remarks/>
        DefineTerminalFailed
        
        '''<remarks/>
        TerminalIdIsNotSpecified
        
        '''<remarks/>
        TerminalSerialNoIsNotSpecified
        
        '''<remarks/>
        DuplicateTerminalId
        
        '''<remarks/>
        TerminalDoesNotExist
        
        '''<remarks/>
        TerminalSerialNumberisInUse
        
        '''<remarks/>
        PeerTypeIsNotSpecified
        
        '''<remarks/>
        PeerNameIsNotSpecified
        
        '''<remarks/>
        InstFeeSchemeNotFound
        
        '''<remarks/>
        FeeSchemaNotDefine
        
        '''<remarks/>
        TMSScheduleTypeNotSpecified
        
        '''<remarks/>
        TelephoneNumberTypeNotSpecified
        
        '''<remarks/>
        TelephoneNumberNotSpecified
        
        '''<remarks/>
        TerminalAlreadyHaveTMSParameter
        
        '''<remarks/>
        ScheduleDateTimeNotSpecified
        
        '''<remarks/>
        TerminalDataTypeNotTMS
        
        '''<remarks/>
        TerminalHaveNotTMSParameter
        
        '''<remarks/>
        TerminalIDAlreadyCancelled
        
        '''<remarks/>
        CannotAssignFeeSchema
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservice.aws.soft.eniac/")>  _
    Partial Public Class getFeeSchemaList
        
        Private arg0Field As feeSchemaRq
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property arg0() As feeSchemaRq
            Get
                Return Me.arg0Field
            End Get
            Set
                Me.arg0Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservice.aws.soft.eniac/")>  _
    Partial Public Class assignFeeSchema2CardAcceptorResponse
        
        Private returnField As feeSchemaRs
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property [return]() As feeSchemaRs
            Get
                Return Me.returnField
            End Get
            Set
                Me.returnField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Partial Public Class externalAccountDTO
        
        Private externalAccountBankBranchIDField As Long
        
        Private externalAccountBankIDField As Short
        
        Private externalAccountIDField As String
        
        Private externalAccountNumberField As String
        
        Private externalAccountTitleField As String
        
        Private externallAccountTypeField As accountTypeCodeEnum
        
        Private externallAccountTypeFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property externalAccountBankBranchID() As Long
            Get
                Return Me.externalAccountBankBranchIDField
            End Get
            Set
                Me.externalAccountBankBranchIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property externalAccountBankID() As Short
            Get
                Return Me.externalAccountBankIDField
            End Get
            Set
                Me.externalAccountBankIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property externalAccountID() As String
            Get
                Return Me.externalAccountIDField
            End Get
            Set
                Me.externalAccountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property externalAccountNumber() As String
            Get
                Return Me.externalAccountNumberField
            End Get
            Set
                Me.externalAccountNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property externalAccountTitle() As String
            Get
                Return Me.externalAccountTitleField
            End Get
            Set
                Me.externalAccountTitleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property externallAccountType() As accountTypeCodeEnum
            Get
                Return Me.externallAccountTypeField
            End Get
            Set
                Me.externallAccountTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property externallAccountTypeSpecified() As Boolean
            Get
                Return Me.externallAccountTypeFieldSpecified
            End Get
            Set
                Me.externallAccountTypeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Public Enum accountTypeCodeEnum
        
        '''<remarks/>
        [Default]
        
        '''<remarks/>
        SavingsAccount
        
        '''<remarks/>
        ChequeAccount
        
        '''<remarks/>
        CreditFacility
        
        '''<remarks/>
        UniversalAccount
        
        '''<remarks/>
        InvestmentAccount
        
        '''<remarks/>
        PAN
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Public Enum paymentMethodType
        
        '''<remarks/>
        Offline_File_Txn
        
        '''<remarks/>
        Offline_File_Batch
        
        '''<remarks/>
        Online_Transfer_Txn
        
        '''<remarks/>
        Online_Transfer_Batch
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Public Enum settlementMethodType
        
        '''<remarks/>
        Manual
        
        '''<remarks/>
        Automatic
        
        '''<remarks/>
        TimedAtSpecifiedTime
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://acquirer.ess.eniacsoft.com/")>  _
    Public Enum activeInactive
        
        '''<remarks/>
        Active
        
        '''<remarks/>
        InActive
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub assignFeeSchema2CardAcceptorCompletedEventHandler(ByVal sender As Object, ByVal e As assignFeeSchema2CardAcceptorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class assignFeeSchema2CardAcceptorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As assignFeeSchema2CardAcceptorResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),assignFeeSchema2CardAcceptorResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub getFeeSchemaListCompletedEventHandler(ByVal sender As Object, ByVal e As getFeeSchemaListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getFeeSchemaListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As getFeeSchemaListResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),getFeeSchemaListResponse)
            End Get
        End Property
    End Class
End Namespace
