'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=PSPMaskanBank;User ID=sa;Password=789789")>  _
        Public ReadOnly Property PSPMaskanBankConnectionString() As String
            Get
                Return CType(Me("PSPMaskanBankConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strTheLatestUserLogin() As String
            Get
                Return CType(Me("strTheLatestUserLogin"),String)
            End Get
            Set
                Me("strTheLatestUserLogin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PSPTejarat_CMSAcceptorManagementService_CMSAcceptorManagementServiceService() As String
            Get
                Return CType(Me("PSPTejarat_CMSAcceptorManagementService_CMSAcceptorManagementServiceService"),String)
            End Get
            Set
                Me("PSPTejarat_CMSAcceptorManagementService_CMSAcceptorManagementServiceService") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.30.29:80/sahand-ws-merchant-administration-service-0.1/AcceptorMan"& _ 
            "agementService")>  _
        Public ReadOnly Property PSPTejarat_CMSAcceptorManagementService_AcceptorManagementServiceService() As String
            Get
                Return CType(Me("PSPTejarat_CMSAcceptorManagementService_AcceptorManagementServiceService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.30.29:80/sahand-ws-merchant-administration-service-0.1/FeeSchemaSe"& _ 
            "rvice")>  _
        Public ReadOnly Property PSPTejarat_CMSFeeSchemaService_FeeSchemaServiceService() As String
            Get
                Return CType(Me("PSPTejarat_CMSFeeSchemaService_FeeSchemaServiceService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.20.46:8080/aws_sina-aws_sina/AcceptorManagementService")>  _
        Public ReadOnly Property PSPTejarat_SinaAcceptorManagementService_AcceptorManagementServiceService() As String
            Get
                Return CType(Me("PSPTejarat_SinaAcceptorManagementService_AcceptorManagementServiceService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.40.27:8080/aws_tejarat-aws_tejarat/FeeSchemaService")>  _
        Public ReadOnly Property PSPTejarat_FeeSchemaService_FeeSchemaServiceService() As String
            Get
                Return CType(Me("PSPTejarat_FeeSchemaService_FeeSchemaServiceService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DATA SOURCE=192.168.50.41/oraisop;PASSWORD=shaparak;USER ID=SHAPARAK")>  _
        Public ReadOnly Property ConnectionString() As String
            Get
                Return CType(Me("ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("YaAt7qHpb9NKXVvXEwmNibCB2eQsj3eWTFgOqM+kq3f+HThrYIQshl86/0BSNCs7Bxf+DiJ30rypJ3kww"& _ 
            "Xm7FBQpu+Hd+aO2WshumXuNz8PsVUcUhrgRvjRZfaHm/cSdDgbTRkg3dlwdjKJ3WfLFQg==")>  _
        Public ReadOnly Property TMSConnectionString() As String
            Get
                Return CType(Me("TMSConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.20.51:8080/aws_tejarat-aws_tejarat/AcceptorManagementService")>  _
        Public ReadOnly Property PSPShaparak_AcceptorManagementService_AcceptorManagementServiceService() As String
            Get
                Return CType(Me("PSPShaparak_AcceptorManagementService_AcceptorManagementServiceService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.8.101.100/webservices/customer.asmx")>  _
        Public ReadOnly Property PSPShaparak_ArianaCustomerService_Customer() As String
            Get
                Return CType(Me("PSPShaparak_ArianaCustomerService_Customer"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.8.101.100/webservices/terminalservices.asmx")>  _
        Public ReadOnly Property PSPShaparak_ArianaTerminalService_TerminalServices() As String
            Get
                Return CType(Me("PSPShaparak_ArianaTerminalService_TerminalServices"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\workspace\shaparak\Release\R 1.15\Src\PSP\PSP\bin\Debug")>  _
        Public Property ContractDocImg_Path() As String
            Get
                Return CType(Me("ContractDocImg_Path"),String)
            End Get
            Set
                Me("ContractDocImg_Path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("22")>  _
        Public Property Fanava_CmsProjectID() As String
            Get
                Return CType(Me("Fanava_CmsProjectID"),String)
            End Get
            Set
                Me("Fanava_CmsProjectID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("118")>  _
        Public Property Fanava_AccountTypeID() As String
            Get
                Return CType(Me("Fanava_AccountTypeID"),String)
            End Get
            Set
                Me("Fanava_AccountTypeID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2100631")>  _
        Public Property Fanava_BranchID() As String
            Get
                Return CType(Me("Fanava_BranchID"),String)
            End Get
            Set
                Me("Fanava_BranchID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("23")>  _
        Public Property Pasargard_CmsProjectID() As String
            Get
                Return CType(Me("Pasargard_CmsProjectID"),String)
            End Get
            Set
                Me("Pasargard_CmsProjectID") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ZIfaagFTnewtd3fq4yLS7c9xKZnDYCwtaMgmUAIH6nxf2uwDrKvWhrLYS6fPrxtE0nhiXIPP3BoJu/iZV"& _ 
            "UN17p5mov8LiGYXrW5TWuAC6e/gr2TC8FAwqsd4VvnjcweoYZUUiz0w4YxqBHv2qZgsAQ==")>  _
        Public ReadOnly Property strConnectionString() As String
            Get
                Return CType(Me("strConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.50.27:2412/api/v1/")>  _
        Public Property WebPosURL() As String
            Get
                Return CType(Me("WebPosURL"),String)
            End Get
            Set
                Me("WebPosURL") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.My.MySettings
            Get
                Return Global.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
